site_name: Toolkit
site_url: https://toolkit.fcrozetta.dev
repo_url: https://github.com/fcrozetta/toolkit
repo_name: fcrozetta/toolkit
copyright: Copyright &copy; 2024 Fernando Crozetta
plugins:
  - search

  - tags:
      tags_file: _tags.md
extra:
  tags:
    python: python
    rust: rust
    beta: beta
    cpp: cpp
    wip: wip
    svelte: svelte
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fcrozetta
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/crozetta
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      title: On this page

theme:
  icon:
    tag:
      python: material/language-python
      rust: material/language-rust
      beta: material/flask
      cpp: material/language-cpp
      wip: material/beaker-alert
      svelte: material/language-html5
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.tabs.link
    - toc.follow
    - toc.integrate

  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
